import { 
  formatDate, 
  getReportStyles, 
  getHeaderHtml, 
  getKpisHtml, 
  getAlcanceHtml, 
  getCierreHtml, 
  getHitosHtml, 
  getRisksHtml, 
  getIncidentsHtml, 
  getCrHtml, 
  getLessonsHtml, 
  getTimelineHtml, 
  getCommentsHtml 
} from './reportHtmlComponents';

export const generateProjectReport = (project, comments, reportOptions, t, lang = 'es') => {
  if (!project) return;

  const tr = t || ((key, opts) => key);
  const importantComments = comments.filter(c => c.es_importante);
  const calc = project.calculations || {};

  // Milestones (from tasks that are hitos)
  const allTasks = project.Tareas || [];
  const milestones = allTasks.filter(t => t.es_hito);
  const completed = milestones.filter(t => t.estado === 'COMPLETADA')
    .sort((a, b) => new Date(b.fecha_limite) - new Date(a.fecha_limite))
    .slice(0, 3);
  const pending = milestones.filter(t => t.estado === 'PENDIENTE')
    .sort((a, b) => new Date(a.fecha_limite) - new Date(b.fecha_limite))
    .slice(0, 3);

  const kpisHtml = getKpisHtml(project, calc, reportOptions, tr);
  const alcanceHtml = getAlcanceHtml(project, reportOptions, tr);
  const cierreHtml = getCierreHtml(project, reportOptions, tr);
  const hitosHtml = getHitosHtml(completed, pending, reportOptions, tr);
  const risksHtml = getRisksHtml(project.Riesgos || [], reportOptions, tr);
  const incidentsHtml = getIncidentsHtml(project.Incidencias || [], reportOptions, tr);
  const crHtml = getCrHtml(project.CambiosAlcance || [], reportOptions, tr);
  const lessonsHtml = getLessonsHtml(project.LeccionesAprendidas || [], reportOptions, tr);

  const sortedTimelineEvents = [...allTasks].sort((a, b) => new Date(a.fecha_limite) - new Date(b.fecha_limite));
  const timelineHtml = getTimelineHtml(sortedTimelineEvents, reportOptions, tr);
  const commentsHtml = getCommentsHtml(importantComments, reportOptions, tr);

  const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <title>${tr('reportExport.projectReportTitle', { id: project.id_proyecto })}</title>
  <style>
    ${getReportStyles()}
  </style>
</head>
<body>
  <button class="print-btn no-print" onclick="window.print()">${tr('reportExport.printSavePdf')}</button>

  ${getHeaderHtml(project, tr)}
  ${kpisHtml}
  ${alcanceHtml}
  ${cierreHtml}
  ${hitosHtml}
  ${timelineHtml}
  ${risksHtml}
  ${incidentsHtml}
  ${crHtml}
  ${lessonsHtml}
  ${commentsHtml ? `
  <div class="section">
    <h2>⭐ ${tr('reportExport.executiveWall')}</h2>
    ${commentsHtml}
  </div>` : ''}

  <div style="margin-top:40px;padding-top:16px;border-top:2px solid #eee;font-size:11px;color:#999;text-align:center;">
    ${tr('reportExport.autoGeneratedOn', { date: formatDate(new Date().toISOString()), time: new Date().toLocaleTimeString(lang === 'pt' ? 'pt-PT' : lang === 'en' ? 'en-US' : 'es-ES', {hour:'2-digit', minute:'2-digit'}) })}
  </div>
</body>
</html>`;

  const reportWindow = window.open('', '_blank');
  if (reportWindow) {
    reportWindow.document.write(html);
    reportWindow.document.close();
  }
};

